---
grails:
    profile: web
    codegen:
        defaultPackage: cytomine.core
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        grailsVersion: '@info.app.grailsVersion@'
        version: '@info.app.version@'
        #        TODO: (Migration) Code de migration de version
        versionDate: 20200213
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

